export const FETCH_DESTINATION_DETAILS = "FETCH_DESTINATION_DETAILS";
export const FETCH_DESTINATION_DETAILS_SUCCESS = "FETCH_DESTINATION_DETAILS_SUCCESS";
export const FETCH_DESTINATION_DETAILS_FAILURE = "FETCH_DESTINATION_DETAILS_FAILURE";


export default {
    FETCH_DESTINATION_DETAILS,
    FETCH_DESTINATION_DETAILS_FAILURE,
    FETCH_DESTINATION_DETAILS_SUCCESS
}

