export const FETCH_DISCOVER_PHOTOS_API = "FETCH_DISCOVER_PHOTOS_API";
export const FETCH_DISCOVER_PHOTOS_API_FAILURE = "FETCH_DISCOVER_PHOTOS_API_FAILURE";
export const FETCH_DISCOVER_PHOTOS_API_SUCCESS = "FETCH_DISCOVER_PHOTOS_API_SUCCESS";
export const FETCH_ADDITIONAL_PHOTOS_API = "FETCH_ADDITIONAL_PHOTOS_API";
export const FETCH_ADDITIONAL_PHOTOS_API_SUCCESS = "FETCH_ADDITIONAL_PHOTOS_API_SUCCESS";
export const FETCH_ADDITIONAL_PHOTOS_API_ERROR = "FETCH_ADDITIONAL_PHOTOS_API_ERROR";


export default {
    FETCH_DISCOVER_PHOTOS_API,
    FETCH_DISCOVER_PHOTOS_API_FAILURE,
    FETCH_DISCOVER_PHOTOS_API_SUCCESS,
    FETCH_ADDITIONAL_PHOTOS_API,
    FETCH_ADDITIONAL_PHOTOS_API_ERROR,
    FETCH_ADDITIONAL_PHOTOS_API_SUCCESS
}

