export const FETCH_DESTINATION_DETAILS = "FETCH_DESTINATION_DETAILS";
export const FETCH_DESTINATION_DETAILS_SUCCESS = "FETCH_DESTINATION_DETAILS_SUCCESS";
export const FETCH_DESTINATION_DETAILS_FAILURE = "FETCH_DESTINATION_DETAILS_FAILURE";
export const FETCH_ADVICE_ACTIVITY_DETAILS = "FETCH_ADVICE_ACTIVITY_DETAILS_SUCCESS";
export const FETCH_ADVICE_ACTIVITY_DETAILS_SUCCESS = 'FETCH_ADVICE_ACTIVITY_DETAILS_SUCCESS'

export default {
    FETCH_DESTINATION_DETAILS,
    FETCH_DESTINATION_DETAILS_FAILURE,
    FETCH_DESTINATION_DETAILS_SUCCESS,
    FETCH_ADVICE_ACTIVITY_DETAILS_SUCCESS,
    FETCH_ADVICE_ACTIVITY_DETAILS
}

